services:
  selenium-hub:
    image: selenium/hub:4.40.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - grid

  node-chrome:
    image: selenium/node-chrome:4.40.0
    container_name: node-chrome
    shm_size: 2g
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_HEADLESS: "true"
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"
      SE_OPTS: "--no-sandbox --disable-dev-shm-usage --disable-gpu --headless=new --disable-features=VizDisplayCompositor"
    networks:
      - grid

  node-firefox:
    image: selenium/node-firefox:4.40.0
    container_name: node-firefox
    shm_size: 2g
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_HEADLESS: "true"
      SE_OPTS: "--no-sandbox --disable-dev-shm-usage --disable-gpu --headless"
    networks:
      - grid

networks:
  grid:
    driver: bridge
